import type { Lang, PatientStatus, Presence, Profile, ThemeKey, UserKey, ViewKey, WorkspaceKey } from '@/types';

export const users: Profile[] = [
  { key: 'valeriia', name: 'Valeriia', role: 'Owner' },
  { key: 'behnia', name: 'Behnia', role: 'Planner' },
  { key: 'ilayda', name: 'İlayda', role: 'Planner' },
  { key: 'manager', name: 'Fırat', role: 'Manager' }
];

export const workspaces: WorkspaceKey[] = ['valeriia', 'behnia', 'ilayda'];

export const workspaceNames: Record<WorkspaceKey, string> = {
  valeriia: 'Valeriia',
  behnia: 'Behnia',
  ilayda: 'İlayda'
};

export const languageNames: Record<Lang, string> = {
  ru: 'Русский',
  en: 'English',
  tr: 'Türkçe',
  fa: 'فارسی'
};

export const themeNames: Record<ThemeKey, string> = {
  paper: 'Paper',
  ocean: 'Ocean',
  forest: 'Forest',
  sakura: 'Sakura',
  night: 'Night',
  swamp: 'Dark Swamp',
  burgundy: 'Dark Burgundy'
};

export const whatsappTargets: Partial<Record<WorkspaceKey, { name: string; phone: string }>> = {
  behnia: { name: 'Behnia', phone: '905428752753' },
  ilayda: { name: 'İlayda', phone: '905422669522' }
};

export const viewKeys: ViewKey[] = ['today', 'patients', 'chats', 'plans', 'reports', 'settings'];
export const statusKeys: PatientStatus[] = ['review', 'correction', 'approved', 'sent', 'archived'];
export const presenceKeys: Presence[] = ['here', 'break', 'lunch', 'busy', 'finished'];

export const roleLabels: Record<Lang, Record<UserKey, string>> = {
  ru: { valeriia: 'Руководитель', behnia: 'Планировщик', ilayda: 'Планировщик', manager: 'Менеджер' },
  en: { valeriia: 'Owner', behnia: 'Planner', ilayda: 'Planner', manager: 'Manager' },
  tr: { valeriia: 'Yönetici', behnia: 'Planlayıcı', ilayda: 'Planlayıcı', manager: 'Müdür' },
  fa: { valeriia: 'مدیر', behnia: 'برنامه ریز', ilayda: 'برنامه ریز', manager: 'مدیر' }
};

export const copy = {
  ru: {
    appTitle: 'DentFlow',
    appSubtitle: 'Рабочее пространство команды',
    welcome: 'Добро пожаловать',
    welcomeText: 'Хорошего рабочего дня и спокойных планов лечения.',
    chooseUser: 'Выберите пользователя',
    language: 'Язык',
    theme: 'Тема',
    exit: 'Выйти',
    cloudOn: 'Облачная синхронизация активна',
    localMode: 'Локальный режим: Firebase не настроен',
    search: 'Поиск пациента, ссылки Canva, карты или сообщения',
    today: 'Сегодня',
    patients: 'Пациенты',
    chats: 'Чаты',
    plans: 'Планы лечения',
    reports: 'Отчеты',
    settings: 'Настройки',
    attention: 'Требуют внимания',
    waiting: 'Ожидают',
    approved: 'Одобрены',
    sent: 'Отправлены',
    newPatients: 'Новые пациенты',
    messages: 'сообщений',
    message: 'Сообщение',
    patientName: 'Имя пациента',
    patientCard: 'Карта пациента',
    canvaLink: 'Ссылка Canva',
    attachFile: 'Прикрепить файл',
    send: 'Отправить',
    noMessages: 'Сообщений пока нет',
    patientPanel: 'Карточка пациента',
    selectPatient: 'Выберите пациента или создайте его из сообщения.',
    doctor: 'Доктор',
    agent: 'Агент',
    notes: 'Заметки',
    status: 'Статус',
    workflow: 'Процесс',
    workflowText: 'Менеджер проверяет кейс, планировщик готовит план, затем Valeriia или менеджер отмечают одобрение и отправку.',
    exportCsv: 'Экспорт CSV',
    exportJson: 'JSON backup',
    sound: 'Звук',
    on: 'Включен',
    off: 'Выключен',
    currentStatus: 'Мой статус',
    team: 'Команда',
    newMessage: 'Новое сообщение от',
    file: 'Файл',
    noPatients: 'Пациентов пока нет',
    systemError: 'Ошибка Firebase',
    here: 'Я здесь',
    break: 'Перерыв',
    lunch: 'Обед',
    busy: 'Занят',
    finished: 'Закончил работу',
    review: 'Проверка',
    correction: 'Коррекция',
    archived: 'Архив',
    tasks: 'Задачи',
    addTask: 'Добавить задачу',
    taskPlaceholder: 'Пациент и что нужно сделать',
    patientTaskName: 'Имя и фамилия пациента',
    done: 'Готово',
    emergency: 'Экстренное сообщение',
    emergencyPlaceholder: 'Текст срочного сообщения для всей команды',
    sendEmergency: 'Показать всем',
    emergencyTitle: 'Экстренное сообщение',
    close: 'Закрыть',
    whatsapp: 'WhatsApp',
    sendToWhatsapp: 'Открыть WhatsApp'
  },
  en: {
    appTitle: 'DentFlow',
    appSubtitle: 'Team workspace',
    welcome: 'Welcome',
    welcomeText: 'Have a good workday and calm treatment plans.',
    chooseUser: 'Choose user',
    language: 'Language',
    theme: 'Theme',
    exit: 'Exit',
    cloudOn: 'Cloud sync is active',
    localMode: 'Local mode: Firebase is not configured',
    search: 'Search patient, Canva, card link, or message',
    today: 'Today',
    patients: 'Patients',
    chats: 'Chats',
    plans: 'Treatment Plans',
    reports: 'Reports',
    settings: 'Settings',
    attention: 'Needs attention',
    waiting: 'Waiting',
    approved: 'Approved',
    sent: 'Sent',
    newPatients: 'New patients',
    messages: 'messages',
    message: 'Message',
    patientName: 'Patient name',
    patientCard: 'Patient Card',
    canvaLink: 'Canva link',
    attachFile: 'Attach file',
    send: 'Send',
    noMessages: 'No messages yet',
    patientPanel: 'Patient card',
    selectPatient: 'Select a patient or create one from a message.',
    doctor: 'Doctor',
    agent: 'Agent',
    notes: 'Notes',
    status: 'Status',
    workflow: 'Workflow',
    workflowText: 'Manager checks the case, planner prepares the plan, then Valeriia or manager marks it approved and sent.',
    exportCsv: 'Export CSV',
    exportJson: 'JSON backup',
    sound: 'Sound',
    on: 'On',
    off: 'Off',
    currentStatus: 'My status',
    team: 'Team',
    newMessage: 'New message from',
    file: 'File',
    noPatients: 'No patients yet',
    systemError: 'Firebase error',
    here: 'Here',
    break: 'Break',
    lunch: 'Lunch',
    busy: 'Busy',
    finished: 'Finished',
    review: 'Review',
    correction: 'Correction',
    archived: 'Archived',
    tasks: 'Tasks',
    addTask: 'Add task',
    taskPlaceholder: 'Patient and what needs to be done',
    patientTaskName: 'Patient first and last name',
    done: 'Done',
    emergency: 'Emergency message',
    emergencyPlaceholder: 'Urgent message for the whole team',
    sendEmergency: 'Show to everyone',
    emergencyTitle: 'Emergency message',
    close: 'Close',
    whatsapp: 'WhatsApp',
    sendToWhatsapp: 'Open WhatsApp'
  },
  tr: {
    appTitle: 'DentFlow',
    appSubtitle: 'Ekip çalışma alanı',
    welcome: 'Hoş geldiniz',
    welcomeText: 'İyi bir iş günü ve sakin tedavi planları dileriz.',
    chooseUser: 'Kullanıcı seç',
    language: 'Dil',
    theme: 'Tema',
    exit: 'Çıkış',
    cloudOn: 'Bulut senkronizasyonu aktif',
    localMode: 'Yerel mod: Firebase ayarlı değil',
    search: 'Hasta, Canva, kart bağlantısı veya mesaj ara',
    today: 'Bugün',
    patients: 'Hastalar',
    chats: 'Sohbetler',
    plans: 'Tedavi Planları',
    reports: 'Raporlar',
    settings: 'Ayarlar',
    attention: 'İlgi gerekenler',
    waiting: 'Bekleyen',
    approved: 'Onaylı',
    sent: 'Gönderildi',
    newPatients: 'Yeni hastalar',
    messages: 'mesaj',
    message: 'Mesaj',
    patientName: 'Hasta adı',
    patientCard: 'Hasta Kartı',
    canvaLink: 'Canva bağlantısı',
    attachFile: 'Dosya ekle',
    send: 'Gönder',
    noMessages: 'Henüz mesaj yok',
    patientPanel: 'Hasta kartı',
    selectPatient: 'Bir hasta seçin veya mesajdan oluşturun.',
    doctor: 'Doktor',
    agent: 'Temsilci',
    notes: 'Notlar',
    status: 'Durum',
    workflow: 'İş akışı',
    workflowText: 'Müdür vakayı kontrol eder, planlayıcı planı hazırlar, sonra Valeriia veya müdür onay ve gönderimi işaretler.',
    exportCsv: 'CSV dışa aktar',
    exportJson: 'JSON yedek',
    sound: 'Ses',
    on: 'Açık',
    off: 'Kapalı',
    currentStatus: 'Durumum',
    team: 'Ekip',
    newMessage: 'Yeni mesaj gönderen',
    file: 'Dosya',
    noPatients: 'Henüz hasta yok',
    systemError: 'Firebase hatası',
    here: 'Buradayım',
    break: 'Mola',
    lunch: 'Öğle yemeği',
    busy: 'Meşgul',
    finished: 'Bitirdi',
    review: 'İnceleme',
    correction: 'Düzeltme',
    archived: 'Arşiv',
    tasks: 'Görevler',
    addTask: 'Görev ekle',
    taskPlaceholder: 'Hasta ve yapılacak iş',
    patientTaskName: 'Hastanın adı ve soyadı',
    done: 'Tamam',
    emergency: 'Acil mesaj',
    emergencyPlaceholder: 'Tüm ekip için acil mesaj',
    sendEmergency: 'Herkese göster',
    emergencyTitle: 'Acil mesaj',
    close: 'Kapat',
    whatsapp: 'WhatsApp',
    sendToWhatsapp: 'WhatsApp aç'
  },
  fa: {
    appTitle: 'DentFlow',
    appSubtitle: 'فضای کاری تیم',
    welcome: 'خوش آمدید',
    welcomeText: 'روز کاری خوبی داشته باشید و برنامه های درمانی آرامی بسازید.',
    chooseUser: 'کاربر را انتخاب کنید',
    language: 'زبان',
    theme: 'تم',
    exit: 'خروج',
    cloudOn: 'همگام سازی ابری فعال است',
    localMode: 'حالت محلی: Firebase تنظیم نشده است',
    search: 'جستجوی بیمار، Canva، لینک کارت یا پیام',
    today: 'امروز',
    patients: 'بیماران',
    chats: 'چت ها',
    plans: 'برنامه های درمان',
    reports: 'گزارش ها',
    settings: 'تنظیمات',
    attention: 'نیازمند توجه',
    waiting: 'در انتظار',
    approved: 'تایید شده',
    sent: 'ارسال شده',
    newPatients: 'بیماران جدید',
    messages: 'پیام ها',
    message: 'پیام',
    patientName: 'نام بیمار',
    patientCard: 'کارت بیمار',
    canvaLink: 'لینک Canva',
    attachFile: 'پیوست فایل',
    send: 'ارسال',
    noMessages: 'هنوز پیامی وجود ندارد',
    patientPanel: 'کارت بیمار',
    selectPatient: 'یک بیمار را انتخاب کنید یا از پیام بسازید.',
    doctor: 'پزشک',
    agent: 'نماینده',
    notes: 'یادداشت ها',
    status: 'وضعیت',
    workflow: 'روند کار',
    workflowText: 'مدیر پرونده را بررسی می کند، برنامه ریز طرح را آماده می کند، سپس Valeriia یا مدیر آن را تایید و ارسال می کند.',
    exportCsv: 'خروجی CSV',
    exportJson: 'پشتیبان JSON',
    sound: 'صدا',
    on: 'روشن',
    off: 'خاموش',
    currentStatus: 'وضعیت من',
    team: 'تیم',
    newMessage: 'پیام جدید از',
    file: 'فایل',
    noPatients: 'هنوز بیماری وجود ندارد',
    systemError: 'خطای Firebase',
    here: 'اینجا هستم',
    break: 'استراحت',
    lunch: 'ناهار',
    busy: 'مشغول',
    finished: 'کار تمام شد',
    review: 'بررسی',
    correction: 'اصلاح',
    archived: 'آرشیو',
    tasks: 'وظایف',
    addTask: 'افزودن وظیفه',
    taskPlaceholder: 'بیمار و کاری که باید انجام شود',
    patientTaskName: 'نام و نام خانوادگی بیمار',
    done: 'انجام شد',
    emergency: 'پیام اضطراری',
    emergencyPlaceholder: 'پیام فوری برای همه تیم',
    sendEmergency: 'نمایش به همه',
    emergencyTitle: 'پیام اضطراری',
    close: 'بستن',
    whatsapp: 'WhatsApp',
    sendToWhatsapp: 'باز کردن WhatsApp'
  }
} satisfies Record<Lang, Record<string, string>>;

export function formatTime(value: number) {
  return new Date(value).toLocaleString([], {
    day: '2-digit',
    month: '2-digit',
    hour: '2-digit',
    minute: '2-digit'
  });
}

export function normalizePatientId(workspace: WorkspaceKey, name: string) {
  const safe = name.trim().toLowerCase().replace(/[^a-z0-9а-яёіїєґ\u0590-\u05ff\u0600-\u06ff]+/gi, '-').replace(/^-|-$/g, '');
  return `${workspace}-${safe || Date.now()}`;
}
